GET http://127.0.0.1:8000/api/login/


POST  http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email" : "aprendiz@example.com",
    "password" : "password123"
}

POST  http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email" : "aprendiz@example.com",
    "password" : "password123"
}

###
POST http://127.0.0.1:8000/api/tareas/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="titulo"

Mi tarea con imagen
------WebKitFormBoundary
Content-Disposition: form-data; name="descripcion"

Descripción de la tarea
------WebKitFormBoundary
Content-Disposition: form-data; name="imagen"; filename="imagen.jpg"
Content-Type: image/jpeg

< ./imagen.jpg
------WebKitFormBoundary--

### SUBIR LA FOTO DE PERFIL A CLOUDINARY

POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpg"
Content-Type: image/jpeg 

C:\Users\SENA\Desktop\el\put-get-delete-post\avatar.jpg
---MiBoundary--